import Head from "next/head";
import { useMyFirstQuery } from "@/redux/services/myFirstApi";
import { SpeedDial } from "primereact/speeddial";
import { Constants } from "@/utils/Constants";

export interface postProps {
  userId: number;
  id: number;
  title: string;
  body: string;
}
export interface errorProps {
  status: number;
  data: any;
}
export interface useMyFirstQueryProps {
  data: postProps[];
  error: errorProps | undefined;
  isLoading: boolean;
}

export default function Home() {
  const constants = new Constants();
  const { data, error, isLoading }: useMyFirstQueryProps | any =
    useMyFirstQuery("posts");

  // const { data, error, isLoading }: any = useMySecondQuery(5);
  // debugger;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-content-end">
          <SpeedDial
            model={constants.items}
            radius={80}
            type="circle"
            buttonClassName="p-button-warning"
          />
        </div>

        <p>{isLoading && "Loading..."}</p>
        {error !== undefined ? (
          error.status
        ) : (
          <ul>
            {data?.map((d: postProps) => (
              <li key={d.id}>{d.title}</li>
            ))}
          </ul>
        )}
      </main>
    </>
  );
}
